name: deploy

on:
  push:
    branches:
      - master  # 触发条件，可以根据需要修改

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-production:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
        # 环境准备
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup pnpm
          uses: pnpm/action-setup@v4
        - name: Setup node
          uses: actions/setup-node@v4
          with:
            node-version: 18
            registry-url: 'https://registry.npmjs.org'
        - name: Get pnpm store directory
          id: pnpm-cache
          run: |
              echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
        - uses: actions/cache@v4
          name: Setup pnpm cache
          with:
              path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
              key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
              restore-keys: |
                ${{ runner.os }}-pnpm-store-
    
        # 构建
        - name: Install dependencies
          run: pnpm install --frozen-lockfile
        - name: Build
          run: pnpm build

        # 部署github-page
        - name: Setup Pages
          uses: actions/configure-pages@v5
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v3
          with:
            path: './docs/.vitepress/dist'
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4

        # 同步到阿里云oss
        - name: setup aliyun oss
          uses: manyuanrong/setup-ossutil@master
          with:
            endpoint: oss-cn-beijing.aliyuncs.com
            access-key-id: ${{ secrets.OSS_KEY_ID }}
            access-key-secret: ${{ secrets.OSS_KEY_SECRET }}
        - name: cp files to aliyun
          run: ossutil cp -rf ./docs/.vitepress/dist oss://${{ secrets.bucket }}/${{ secrets.dir }}
    


      